<?php

return [
    'title' => 'Politique sur les cookies pour',
    'content' => '<p>Quels sont les cookies?</p>
        <p>Comme c\'est pratique habituelle avec presque tous les sites Web professionnels, ce site utilise des cookies, qui sont de minuscules fichiers téléchargés sur votre ordinateur, afin d\'améliorer votre expérience. Cette page décrit les informations recueillies, la façon dont nous l\'utilisons et pourquoi nous devons parfois stocker ces cookies. Nous partagerons également la façon dont vous pouvez éviter que ces cookies ne soient stockés, mais cela risque de dégrader ou de «briser» certains éléments de la fonctionnalité des sites.</p>
        <p>Pour plus d\'informations générales sur les cookies, consultez l\'article de Wikipedia sur les cookies HTTP ...</p>
        <p>Comment utilisons des cookies</p>
        <p>Nous utilisons des cookies pour diverses raisons détaillées ci-dessous. Malheureusement, dans la plupart des cas, il n\'existe aucune option standard de l\'industrie pour désactiver les cookies sans désactiver complètement les fonctionnalités et les fonctionnalités qu\'ils ajoutent à ce site. Il est recommandé de laisser sur tous les cookies si vous ne savez pas si vous en avez besoin ou non au cas où ils sont utilisés pour fournir un service que vous utilisez.</p>
        <p>Désactivation des cookies</p>
        <p>Vous pouvez empêcher le réglage des cookies en ajustant les paramètres de votre navigateur (voir l\'aide de votre navigateur pour savoir comment le faire). Soyez conscient que la désactivation des cookies affectera la fonctionnalité de ce site et de nombreux autres sites que vous visitez. La désactivation des cookies entraînera généralement la désactivation de certaines fonctionnalités et fonctionnalités de ce site. Par conséquent, il est recommandé de ne pas désactiver les cookies.</p>
        <p>Les cookies que nous fixons</p>
        <p>&nbsp;</p>
        <p>Afin de vous fournir une excellente expérience sur ce site, nous fournissons la fonctionnalité pour définir vos préférences quant à la façon dont ce site fonctionne lorsque vous l\'utilisez. Pour se souvenir de vos préférences, nous devons définir les cookies afin que ces informations puissent être appelées chaque fois que vous interagissez avec une page est affectée par vos préférences.</p>
        <p>&nbsp;</p>
        <p>Cookies tiers</p>
        <p>Dans certains cas particuliers, nous utilisons également des cookies fournis par des tiers approuvés. La section suivante détaille les cookies de tiers que vous pourriez rencontrer sur ce site.</p>
        <p>Ce site utilise Google Analytics qui est l\'une des solutions analytiques les plus répandues et les plus fiables sur le Web pour nous aider à comprendre comment vous utilisez le site et les moyens d\'améliorer votre expérience. Ces cookies peuvent suivre des choses telles que combien de temps vous dépensez sur le site et les pages que vous visitez afin que nous puissions continuer à produire du contenu attrayant.</p>
        <p>Pour plus d\'informations sur les cookies Google Analytics, consultez la page officielle Google Analytics.</p>
        <p>De temps en temps, nous testons de nouvelles fonctionnalités et apportons des modifications subtiles à la manière dont le site est livré. Lorsque nous testons encore de nouvelles fonctionnalités, ces cookies peuvent être utilisés pour vous assurer que vous recevez une expérience constante sur le site tout en veillant à ce que nous comprenions quelles optimisations nos utilisateurs apprécient le plus.</p>
        <p>Le service Google AdSense que nous utilisons pour diffuser de la publicité utilise un cookie DoubleClick pour diffuser des annonces plus pertinentes sur le Web et limiter le nombre de fois qu\'une annonce est affichée.</p>
        <p>Pour plus d\'informations sur Google AdSense, consultez la FAQ de confidentialité Google AdSense officielle.</p>
        <p>Nous utilisons des publicités pour compenser les coûts de fonctionnement de ce site et fournir des fonds pour un développement ultérieur. Les cookies de publicité comportementale utilisés par ce site sont conçus pour vous assurer que nous vous fournissons les publicités les plus pertinentes si possible en surveillant anonymement vos intérêts et en présentant des éléments similaires qui pourraient être intéressants.</p>
        <p>Dans certains cas, nous pouvons vous fournir un contenu personnalisé en fonction de ce que vous nous dites sur vous directement ou indirectement en liant un compte de médias sociaux. Ces types de cookies nous permettent simplement de vous fournir un contenu qui, selon nous, pourrait vous intéresser.</p>
        <p>Plusieurs partenaires annoncent en notre nom et les cookies de suivi des affiliés nous permettent simplement de voir si nos clients sont venus sur le site par l\'intermédiaire de l\'un de nos sites partenaires afin que nous puissions les créditer de manière appropriée et, le cas échéant, permettre à nos partenaires affiliés de fournir un bonus qu\'ils pourraient Vous procurer un achat.</p>
        <p>Nous utilisons également des boutons de médias sociaux et / ou des plugins sur ce site qui vous permettent de vous connecter à votre réseau social de diverses façons. Pour que ceux-ci fonctionnent, les sites de médias sociaux suivants incluent: Facebook, Twitter, établira des cookies via notre site qui peut être utilisé pour améliorer votre profil sur leur site ou contribuer aux données qu\'ils détiennent à diverses fins décrites dans leurs politiques de confidentialité respectives.</p>
        <p>&nbsp;</p>
        <p>Plus d\'information</p>
        <p>J\'espère que cela vous a clarifié les choses et, comme cela a été mentionné précédemment, si vous ne savez pas si vous avez besoin ou pas, il est généralement plus sûr de laisser les cookies activés au cas où il interagirait avec l\'une des fonctionnalités que vous utilisez sur notre site. Toutefois, si vous cherchez encore plus d\'informations, vous pouvez nous contacter à travers une de nos méthodes de contact préférées.</p>'
];
